ProxiBusNicWeb/Controllers/BusParadasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProxiBusNicWeb.Models;

namespace ProxiBusNicWeb.Controllers
{
    [Authorize]
    public class BusParadasController : Controller
    {
        private ProxiBusNicEntityContainer db = new ProxiBusNicEntityContainer();

        // GET: BusParadas
        public ActionResult Index()
        {
            IQueryable<BusParada> busParadas = null;
            if (User.IsInRole("UsuarioAnonimo"))
            {
                 busParadas = db.BusParadas.Include(b => b.Parada).Include(b => b.Bus).Where(p => p.Parada.Estado && p.Bus.Estado);
            }
            else
            {
                busParadas = db.BusParadas.Include(b => b.Parada).Include(b => b.Bus);
            }
            
            
            return View(busParadas.ToList());
        }

        // GET: BusParadas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BusParada busParada = db.BusParadas.Find(id);
            if (busParada == null)
            {
                return HttpNotFound();
            }
            return View(busParada);
        }

        // GET: BusParadas/Create
        public ActionResult Create()
        {
            ViewBag.ParadaId = new SelectList(db.Paradas, "Id", "Descripcion");
            ViewBag.BusId = new SelectList(db.Buses, "Id", "NumeroRuta");
            return View();
        }

        // POST: BusParadas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ParadaId,BusId")] BusParada busParada)
        {
            if (ModelState.IsValid)
            {
                db.BusParadas.Add(busParada);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ParadaId = new SelectList(db.Paradas, "Id", "Descripcion", busParada.ParadaId);
            ViewBag.BusId = new SelectList(db.Buses, "Id", "NumeroRuta", busParada.BusId);
            return View(busParada);
        }

        // GET: BusParadas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BusParada busParada = db.BusParadas.Find(id);
            if (busParada == null)
            {
                return HttpNotFound();
            }
            ViewBag.ParadaId = new SelectList(db.Paradas, "Id", "Descripcion", busParada.ParadaId);
            ViewBag.BusId = new SelectList(db.Buses, "Id", "NumeroRuta", busParada.BusId);
            return View(busParada);
        }

        // POST: BusParadas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ParadaId,BusId")] BusParada busParada)
        {
            if (ModelState.IsValid)
            {
                db.Entry(busParada).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ParadaId = new SelectList(db.Paradas, "Id", "Descripcion", busParada.ParadaId);
            ViewBag.BusId = new SelectList(db.Buses, "Id", "NumeroRuta", busParada.BusId);
            return View(busParada);
        }

        // GET: BusParadas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BusParada busParada = db.BusParadas.Find(id);
            if (busParada == null)
            {
                return HttpNotFound();
            }
            return View(busParada);
        }

        // POST: BusParadas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BusParada busParada = db.BusParadas.Find(id);
            db.BusParadas.Remove(busParada);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProxiBusNicWeb/Controllers/BusesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using ProxiBusNicWeb.Models;

namespace ProxiBusNicWeb.Controllers
{
    [Authorize]
    public class BusesController : Controller
    {
        private ProxiBusNicEntityContainer db = new ProxiBusNicEntityContainer();

        // GET: Buses
        public ActionResult Index()
        {
            List<Bus> bus = null;
            if (User.IsInRole("UsuarioAnonimo"))
            {
                bus = db.Buses.Where(b=>b.Estado).ToList();
            }
            else
            {
                bus = db.Buses.ToList();
            }
            return View(bus);
        }

        // GET: Buses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // GET: Buses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Buses/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NumeroRuta,Estado,FotoBus,FechaCreacion,UsuarioCreacion,FechaModificacion,UsuarioModificacion")] Bus bus)
        {
            HttpPostedFileBase foto = Request.Files[0];


            if (foto.ContentLength != 0)
            {
                WebImage web = new WebImage(foto.InputStream);
                bus.FotoBus = web.GetBytes();
            }

            if (ModelState.IsValid)
            {
                db.Buses.Add(bus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bus);
        }

        // GET: Buses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // POST: Buses/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NumeroRuta,Estado,FotoBus,FechaCreacion,UsuarioCreacion,FechaModificacion,UsuarioModificacion")] Bus bus)
        {
            HttpPostedFileBase foto = Request.Files[0];


            if (foto.ContentLength != 0)
            {
                WebImage web = new WebImage(foto.InputStream);
                bus.FotoBus = web.GetBytes();
            }


            if (ModelState.IsValid)
            {
                db.Entry(bus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bus);
        }

        // GET: Buses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // POST: Buses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bus bus = db.Buses.Find(id);
            db.Buses.Remove(bus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProxiBusNicWeb/Controllers/ParadasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using ProxiBusNicWeb.Models;

namespace ProxiBusNicWeb.Controllers
{
    [Authorize]
    public class ParadasController : Controller
    {
        private ProxiBusNicEntityContainer db = new ProxiBusNicEntityContainer();

        // GET: Paradas
        public ActionResult Index()
        {
            List<Parada> paradas = null;
            if (User.IsInRole("UsuarioAnonimo"))
            {
                paradas = db.Paradas.Where(p => p.Estado).ToList();

            }
            else
            {
                paradas = db.Paradas.ToList();
            }
            return View(paradas);
        }

        // GET: Paradas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parada parada = db.Paradas.Find(id);
            if (parada == null)
            {
                return HttpNotFound();
            }
            return View(parada);
        }

        // GET: Paradas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Paradas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descripcion,Alias,FotoParada,Estado,Longitud,Latitud,FechaCreacion,UsuarioCreacion,FechaModificacion,UsuarioModificacion")] Parada parada)
        {
            HttpPostedFileBase foto = Request.Files[0];


            if (foto.ContentLength != 0)
            {
                WebImage web = new WebImage(foto.InputStream);
                parada.FotoParada = web.GetBytes();
            }

            if (ModelState.IsValid)
            {
                db.Paradas.Add(parada);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(parada);
        }

        // GET: Paradas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parada parada = db.Paradas.Find(id);
            if (parada == null)
            {
                return HttpNotFound();
            }
            return View(parada);
        }

        // POST: Paradas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descripcion,Alias,FotoParada,Estado,Longitud,Latitud,FechaCreacion,UsuarioCreacion,FechaModificacion,UsuarioModificacion")] Parada parada)
        {

            HttpPostedFileBase foto = Request.Files[0];
            if (foto.ContentLength != 0)
            {
                WebImage web = new WebImage(foto.InputStream);
                parada.FotoParada = web.GetBytes();
            }

            if (ModelState.IsValid)
            {
                db.Entry(parada).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(parada);
        }

        // GET: Paradas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Parada parada = db.Paradas.Find(id);
            if (parada == null)
            {
                return HttpNotFound();
            }
            return View(parada);
        }

        // POST: Paradas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Parada parada = db.Paradas.Find(id);
            db.Paradas.Remove(parada);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProxiBusNicWeb/Views/nuevas/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-mx">

<head>
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PBN</title>
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <!-- Custom fonts for this template-->

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Content/css/sb-admin-2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">

    @*Todos estos son para datatables*@
    @*<link href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap4.min.css" >*@
    <link href="~/Content/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/vendor/datatables/responsive.bootstrap4.min.css" rel="stylesheet" />
</head>

<body id="page-top">

    @*Este jquery está actualizado a la última versión (3.5.1) *@
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    @*<script src="https://code.jquery.com/jquery-3.5.1.js"></script>*@
   
    <!-- Page Wrapper -->
    <div id="wrapper">

       @Html.Partial("_MenuLateral")


        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                @if (Request.IsAuthenticated)
                {
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">


                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">


                    <div class="topbar-divider d-none d-sm-block"></div>

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">

                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">


                            <span class="mr-2 d-none d-lg-inline text-gray-600 small"> @User.Identity.Name.ToString() </span>
                            <i class="fa-solid fa-user"></i>
                        </a>
                        @Html.Partial("_LoginPartial")

                    </li>

                </ul>

            </nav>
            <!-- End of Topbar -->
                }

                @*CUERPO*@


                <!-- Begin Page Content -->
                <div class="container-fluid">



                    @RenderBody();

                    @*Requerido para cambiar clave*@
                    @RenderSection("scripts", required: false)
                </div>
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; ProxiBusNic @System.DateTime.Now.Year</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">¿Desea cerrar sesión?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Selecciona cerrar sesión si está seguro que desea hacerlo.</div>
                <div class="modal-footer">
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                    @Html.AntiForgeryToken()

                    @*<ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.ActionLink("Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                        </li>
                        
                    </ul>*@
                    }

                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                    <a href="javascript:document.getElementById('logoutForm').submit()">Cerrar sesión</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->

    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    @*<script src="../Content/vendor/chart.js/Chart.min.js"></script>*@


    <!-- Page level custom scripts -->
    <!--<script src="/Content/js/demo/chart-area-demo.js"></script>
    <script src="/Content/js/demo/chart-pie-demo.js"></script>-->

</body>

</html>

ProxiBusNicWeb/Views/nuevas/Shared/_MenuLateral.cshtml
@if (Request.IsAuthenticated)
    {
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">


    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action( "Index", "Home")">
        <div class="sidebar-brand-icon">
            
            <img src="~/Img/OriginalLogo.png" width="100" height="100" />
        </div>

        <div class="sidebar-brand-text mx-2">ProxiBusNic</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="@Url.Action( "Index", "Home")">
            <i class="fa-solid fa-house"></i>
            <span>Inicio</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Opciones
    </div>
 
        <!-- Nav Item - Buses -->
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action( "Index", "Buses")">
                <i class="fa-solid fa-bus-simple"></i>
                <span>Buses</span>
            </a>
        </li>

        <!-- Nav Item - Paradas -->
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action( "Index", "Paradas")">
                <i class="fa-solid fa-street-view"></i>
                <span>Paradas</span>
            </a>
        </li>

        <!-- Nav Item - Buses con paradas -->
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action( "Index", "BusParadas")">
                <i class="fa-solid fa-road"></i>
                <span>Buses con paradas</span>
            </a>
        </li>

        <!-- Nav Item - Buses con paradas -->
        <li class="nav-item">
            <a class="nav-link" href="@Url.Action( "Index", "Sugerencias")">
                <i class="fa-solid fa-circle-info"></i>
                <span>Sugerencias</span>
            </a>
        </li>
    
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>





</ul>
 }
<!-- End of Sidebar -->